// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiuwxdvhpliottrkxniv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdXd4ZHZocGxpb3R0cmt4bml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDAwNzcsImV4cCI6MjA1Nzc3NjA3N30.8tqQO24mhXFqeeZqEVfhg7r5zis_F1rhHnejKo7iAew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);